export default function BarangayOptions() {
  return (
    <>
      <optgroup label="District 1">
        <option value="Alicia">Alicia</option>
        <option value="Amihan">Amihan</option>
        <option value="Apolonio Samson">Apolonio Samson</option>
        <option value="Bahay Toro">Bahay Toro</option>
        <option value="Balingasa">Balingasa</option>
        <option value="Bungad">Bungad</option>
        <option value="Damar">Damar</option>
        <option value="Damayan">Damayan</option>
        <option value="Del Monte">Del Monte</option>
        <option value="Katipunan">Katipunan</option>
        <option value="Lourdes">Lourdes</option>
        <option value="Maharlika">Maharlika</option>
        <option value="Manresa">Manresa</option>
        <option value="Mariblo">Mariblo</option>
        <option value="Masambong">Masambong</option>
        <option value="N.S. Amoranto">N.S. Amoranto</option>
        <option value="Nayong Kanluran">Nayong Kanluran</option>
        <option value="Paang Bundok">Paang Bundok</option>
        <option value="Pag-ibig sa Nayon">Pag-ibig sa Nayon</option>
        <option value="Paltok">Paltok</option>
        <option value="Paraiso">Paraiso</option>
        <option value="Phil-Am">Phil-Am</option>
        <option value="Project 6">Project 6</option>
        <option value="Ramon Magsaysay">Ramon Magsaysay</option>
        <option value="Saint Peter">Saint Peter</option>
        <option value="Salvacion">Salvacion</option>
        <option value="San Antonio">San Antonio</option>
        <option value="San Isidro Labrador">San Isidro Labrador</option>
        <option value="San Jose">San Jose</option>
        <option value="Santa Cruz">Santa Cruz</option>
        <option value="Santa Teresita">Santa Teresita</option>
        <option value="Santo Cristo">Santo Cristo</option>
        <option value="Santo Domingo">Santo Domingo</option>
        <option value="Siena">Siena</option>
        <option value="Talayan">Talayan</option>
        <option value="Vasra">Vasra</option>
        <option value="Veterans Village">Veterans Village</option>
        <option value="West Triangle">West Triangle</option>
      </optgroup>
      <optgroup label="District 2">
        <option value="Bagong Silangan">Bagong Silangan</option>
        <option value="Batasan Hills">Batasan Hills</option>
        <option value="Commonwealth">Commonwealth</option>
        <option value="Holy Spirit">Holy Spirit</option>
        <option value="Payatas">Payatas</option>
      </optgroup>
      <optgroup label="District 3">
        <option value="Bagumbayan">Bagumbayan</option>
        <option value="Bagumbuhay">Bagumbuhay</option>
        <option value="Bayanihan">Bayanihan</option>
        <option value="Blue Ridge A">Blue Ridge A</option>
        <option value="Blue Ridge B">Blue Ridge B</option>
        <option value="Camp Aguinaldo">Camp Aguinaldo</option>
        <option value="Claro">Claro</option>
        <option value="Dioquino Zobel">Dioquino Zobel</option>
        <option value="Duyan-Duyan">Duyan-Duyan</option>
        <option value="E. Rodriguez">E. Rodriguez</option>
        <option value="East Kamias">East Kamias</option>
        <option value="Escopa I">Escopa I</option>
        <option value="Escopa II">Escopa II</option>
        <option value="Escopa III">Escopa III</option>
        <option value="Escopa IV">Escopa IV</option>
        <option value="Libis">Libis</option>
        <option value="Loyola Heights">Loyola Heights</option>
        <option value="Mangga">Mangga</option>
        <option value="Marilag">Marilag</option>
        <option value="Masagana">Masagana</option>
        <option value="Matandang Balara">Matandang Balara</option>
        <option value="Milagrosa">Milagrosa</option>
        <option value="Pansol">Pansol</option>
        <option value="Quirino 2-A">Quirino 2-A</option>
        <option value="Quirino 2-B">Quirino 2-B</option>
        <option value="St.Ignatius">St.Ignatius</option>
        <option value="San Roque">San Roque</option>
        <option value="Silangan">Silangan</option>
        <option value="Socorro">Socorro</option>
        <option value="Tagumpay">Tagumpay</option>
        <option value="Ugong Norte">Ugong Norte</option>
        <option value="Villa Maria Clara">Villa Maria Clara</option>
        <option value="West Kamias">West Kamias</option>
        <option value="White Plains">White Plains</option>
      </optgroup>
      <optgroup label="District 4">
        <option value="Bagong Lipunan ng Crame">Bagong Lipunan ng Crame</option>
        <option value="Botocan">Botocan</option>
        <option value="Central">Central</option>
        <option value="Damayang Lagi">Damayang Lagi</option>
        <option value="Don Manuel">Don Manuel</option>
        <option value="Doña Aurora">Doña Aurora</option>
        <option value="Doña Imelda">Doña Imelda</option>
        <option value="Doña Josefa">Doña Josefa</option>
        <option value="Horseshoe">Horseshoe</option>
        <option value="Immaculate Conception">Immaculate Conception</option>
        <option value="Kalusugan">Kalusugan</option>
        <option value="Kamuning">Kamuning</option>
        <option value="Kaunlaran">Kaunlaran</option>
        <option value="Kristong Hari">Kristong Hari</option>
        <option value="Krus na Ligas">Krus na Ligas</option>
        <option value="Laging Handa">Laging Handa</option>
        <option value="Malaya">Malaya</option>
        <option value="Mariana">Mariana</option>
        <option value="Obrero">Obrero</option>
        <option value="Old Capitol Site">Old Capitol Site</option>
        <option value="Paligsahan">Paligsahan</option>
        <option value="Pinagkaisahan">Pinagkaisahan</option>
        <option value="Piñahan">Piñahan</option>
        <option value="Roxas">Roxas</option>
        <option value="Sacred Heart">Sacred Heart</option>
        <option value="San Isidro Galas">San Isidro Galas</option>
        <option value="San Martin de Porres">San Martin de Porres</option>
        <option value="San Vicente">San Vicente</option>
        <option value="Santo Niño">Santo Niño</option>
        <option value="Santol">Santol</option>
        <option value="Sikatuna Village">Sikatuna Village</option>
        <option value="South Triangle">South Triangle</option>
        <option value="Tatalon">Tatalon</option>
        <option value="Teachers Village East">Teachers Village East</option>
        <option value="Teachers Village West">Teachers Village West</option>
        <option value="U.P. Campus">U.P. Campus</option>
        <option value="U.P. Village">U.P. Village</option>
        <option value="Valencia">Valencia</option>
      </optgroup>
      <optgroup label="District 5">
        <option value="Bagbag">Bagbag</option>
        <option value="Capri">Capri</option>
        <option value="Fairview">Fairview</option>
        <option value="Greater Lagro">Greater Lagro</option>
        <option value="Gulod">Gulod</option>
        <option value="Kaligayahan">Kaligayahan</option>
        <option value="Nagkaisang Nayon">Nagkaisang Nayon</option>
        <option value="North Fairview">North Fairview</option>
        <option value="Novaliches Proper">Novaliches Proper</option>
        <option value="Pasong Putik Proper">Pasong Putik Proper</option>
        <option value="San Agustin">San Agustin</option>
        <option value="San Bartolome">San Bartolome</option>
        <option value="Santa Lucia">Sta Lucia</option>
        <option value="Santa Monica">Sta Monica</option>
      </optgroup>
      <optgroup label="District 6">
        <option value="Apolonio Samson">Apolonio Samson</option>
        <option value="Baesa">Baesa</option>
        <option value="Balon-Bato">Balon-Bato</option>
        <option value="Culiat">Culiat</option>
        <option value="New Era">New Era</option>
        <option value="Pasong Tamo">Pasong Tamo</option>
        <option value="Sangandaan">Sangandaan</option>
        <option value="Sauyo">Sauyo</option>
        <option value="Talipapa">Talipapa</option>
        <option value="Tandang Sora">Tandang Sora</option>
        <option value="Unang Sigaw">Unang Sigaw</option>
      </optgroup>
    </>
  );
}
